### ISSUE TITLE
SMTP Connection

### ISSUE THREAD

**Issue by hillsinfoodle** [clearflask/clearflask#130] opened 2023-12-14 01:18 UTC
I've just installed a docker based instance and am encountering issues configuring SMTP. This instance is from the latest docker containers ( ghcr.io/clearflask/clearflask-server:latest ) or rather a copy from yesterday.

My configuration:
```
com.smotana.clearflask.core.push.provider.EmailServiceImpl$Config.smtpStrategy=SMTP_TLS
com.smotana.clearflask.core.push.provider.EmailServiceImpl$Config.smtpHost=smtp.sparkpostmail.com
com.smotana.clearflask.core.push.provider.EmailServiceImpl$Config.smtpPort=587
com.smotana.clearflask.core.push.provider.EmailServiceImpl$Config.smtpUser=SMTP_Injection
com.smotana.clearflask.core.push.provider.EmailServiceImpl$Config.smtpPassword=redacted
com.smotana.clearflask.core.push.provider.EmailServiceImpl$Config.emailDisplayName=displayname
com.smotana.clearflask.core.push.provider.EmailServiceImpl$Config.fromEmailLocalPart=noreply
com.smotana.clearflask.core.push.provider.EmailServiceImpl$Config.fromEmailDomainOverride=redacted.com

```
the container itself (clearflask-server) can connect (have tested with nmap) on the cli. However when the web app tries to connect I see logs such as:

> Caused by: javax.mail.MessagingException: Could not connect to SMTP host: smtp.sparkpostmail.com, port: 587
> Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
> 

The server requires TLSv1.2 which is not mentioned as disabled in the java.security file and it seems likely this is the correct configuration and a "workable" situation.

```
openssl s_client -connect smtp.sparkpostmail.com:587 -starttls smtp
```
**Server response snippit:**
> -----END CERTIFICATE-----
> subject=CN = *.sparkpostmail.com
> 
> issuer=C = US, O = DigiCert Inc, OU = www.digicert.com, CN = RapidSSL TLS RSA CA G1
> 
> 
> No client certificate CA names sent
> Peer signing digest: SHA256
> Peer signature type: RSA
> Server Temp Key: ECDH, P-256, 256 bits
> 
> SSL handshake has read 4579 bytes and written 473 bytes
> Verification: OK
> 
> New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
> Server public key is 2048 bit
> Secure Renegotiation IS supported
> Compression: NONE
> Expansion: NONE
> No ALPN negotiated
> SSL-Session:
>     Protocol  : TLSv1.2
>     Cipher    : ECDHE-RSA-AES256-GCM-SHA384

An item I see that may be an issue is the wildcard certificate?

I have followed a suggestion from a previous query on this topic and added the following env var to the server container, however am not seeing any related logs.
```
`JAVA_OPTS="-Djavax.net.debug=ssl"`
```

I have also followed the email providers suggestions, no joy: https://support.sparkpost.com/docs/faq/smtp-connection-problems

Can anyone provide some additional suggestions for debugging?

**Comment by hillsinfoodle** [comment] 2023-12-14 04:18
More complete log:

> 04:17:09.086 [pool-28-thread-1] TRACE o.s.m.i.AbstractProxyServerSyncingClosure - all threads have finished processing
> 04:17:09.086 [pool-28-thread-1] ERROR o.s.i.u.c.AsyncOperationHelper - Failed to run sendMail process
> org.simplejavamail.mailer.internal.MailerException: Third party error
> 	at org.simplejavamail.mailer.internal.SendMailClosure.executeClosure(SendMailClosure.java:91)
> 	at org.simplejavamail.mailer.internal.AbstractProxyServerSyncingClosure.run(AbstractProxyServerSyncingClosure.java:56)
> 	at org.simplejavamail.internal.util.concurrent.AsyncOperationHelper$1.run(AsyncOperationHelper.java:75)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> Caused by: javax.mail.MessagingException: Could not convert socket to TLS
> 	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:1907)
> 	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:666)
> 	at javax.mail.Service.connect(Service.java:317)
> 	at javax.mail.Service.connect(Service.java:176)
> 	at javax.mail.Service.connect(Service.java:125)
> 	at org.simplejavamail.mailer.internal.util.TransportRunner.runOnSessionTransport(TransportRunner.java:75)
> 	at org.simplejavamail.mailer.internal.util.TransportRunner.sendMessage(TransportRunner.java:48)
> 	at org.simplejavamail.mailer.internal.SendMailClosure.executeClosure(SendMailClosure.java:82)
> 	... 7 common frames omitted
> Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
> 	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1696)
> 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1514)
> 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1416)
> 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
> 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
> 	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:549)
> 	at com.sun.mail.util.SocketFetcher.startTLS(SocketFetcher.java:486)
> 	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:1902)
> 	... 14 common frames omitted
> Caused by: java.io.EOFException: SSL peer shut down incorrectly
> 	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:483)
> 	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
> 	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
> 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
> 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
> 	... 20 common frames omitted
>

**Comment by hillsinfoodle** [comment] 2023-12-14 21:50
I have now tested this with sendgrid and get the same behaviour, tested on port 25 with smtp and ssl on 465 no difference in behaviour besides the reported transport.

**Comment by hillsinfoodle** [comment] 2024-01-17 20:48
@matusfaro is this something you may be able to replicate / test on an instance?

Realise it is a busy time of year.

Thank you

**Comment by matusfaro** [comment] 2024-01-17 20:58
@hillsinfoodle Hey sorry, you could try adding the debug using this method:
https://github.com/clearflask/clearflask/issues/60#issuecomment-1113922543

Also, maybe you are using the wrong protocol here, can you try to modify `smtpStrategy`:
https://github.com/clearflask/clearflask/issues/60#issuecomment-1118238421

Sorry I can't spend more time on this now. I'll see if I have more time later.

**Comment by hillsinfoodle** [comment] 2024-01-25 22:40
Thanks @matusfaro no problem we are just assessing this for use still and treading lightly, have attempted both of these, will leave this open for now and come back once I've had more time to look.

Anyone who is using a public email service able to confirm which one they're using?

**Comment by matusfaro** [comment] 2024-01-29 15:25
@hillsinfoodle You can try the latest version 1.6.12 that bumps up the dependencies and explicitly uses TLSv1.2. Can be bumped up to TLSv1.3 via new [configuration property](https://github.com/clearflask/clearflask/blob/master/clearflask-server/src/main/java/com/smotana/clearflask/core/push/provider/EmailServiceImpl.java#L89)

Sorry it took a while to get to this. SMTP was a community requested feature and it hasn't been battle-tested. I do offer priority support for self-hosting if that interests you and of course the cloud version is fully supported.

**Comment by matusfaro** [comment] 2024-02-22 19:10
Closing as duplicate of #134

**Closed** 2024-02-22 19:10 UTC
